### ISSUE TITLE
PEtab SciML TODO

### ISSUE THREAD

**Issue by sebapersson** [sebapersson/petab_sciml#11]
This issue acts as a TODO on things to complete for the standard:

- [ ] Add different `initializationPriors`. In addition the the supported priors in PEtab we should add `glorot_normal`, `glorot_uniform` as well as `kaiming_normal` and `kaiming_uniform`, where for the latter users will have to specify the gain. Need to add test cases for this.
- [ ] Add ability to set  initialization for a layer via the parameters table. The following should be allowed in the parameters table: `netId.layerId`. Need to add test cases for this.
- [ ] Add test case where neural network parameters are constant (not estimated). 
- [ ] Following #4, specify neural network output in the condition table. This will wait for PEtab v2 spec completion.
- [ ] Update the specification for PEtab SciML, and host it online in this repository. Usually I use Julia Documenter.jl for hosting docs, but I guess we should use something Python based for consistency?
- [ ] Update to use the code in `src/python/petab_sciml `for setting up the test cases.
- [ ] Add repository tests, specifically add tests to test the consistency between Lux.jl and PyTorch (this is already done in the net test-cases, but this should be refactored to a proper test directory). Might also be worthwhile the test round-trip for the yaml specification with PyTorch?

Feel free to add any more points you might find relevant. Once the above points are addressed, I think the extension should be close to complete.

**Comment by FFroehlich** [comment]
sorry to be that guy, but in the testcases
- "model_files" needs to be a key value pairs with the model id as key
- petabEntityId and modelEntityId are swapped

**Comment by sebapersson** [comment]
> sorry to be that guy, but in the testcases

Thanks for noticing, at least this is easy to fix. I will look at this tomorrow.

**Comment by FFroehlich** [comment]
> > sorry to be that guy, but in the testcases
> 
> Thanks for noticing, at least this is easy to fix. I will look at this tomorrow. As for the model id, in this case should it match the id in the SBML file? (SBML model name)

I don't think the model id is used anywhere at this point (but could be referred to in `modelEntityId`)

**Comment by sebapersson** [comment]
@FFroehlich the formatting issues are now fixed with #12

**Comment by dilpath** [comment]
A neural ODE has a NN that takes the state as input, and outputs a vector of the same size.

Do we support assigning the ODE state as the NN input, or do we need to assign each state variable individually to each NN input node? Being able to use the full state vector could be nice, but there is no ID for this yet, to use in the hybridization table.
